import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Beaker, Calculator, Search, Star, Trash2, X, Plus, FlaskConical } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../lib/api";
const EMPTY_FORM={name:"",formula:"",density:"",atomic_number:"",atomic_mass:"",particle_size_nm:"",crystal_structure:"",manufacturer:"",research_notes:""};
export default function Materials(){
 const navigate=useNavigate(); const [materials,setMaterials]=useState([]); const [loading,setLoading]=useState(true); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState(EMPTY_FORM); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [favorites,setFavorites]=useState(()=>{try{return JSON.parse(localStorage.getItem("nanomed_favorite_materials")||"[]")}catch{return[]}});
 const load=async()=>{setLoading(true);try{const {data}=await api.get("/materials");setMaterials(data||[])}catch(e){setError("Could not load materials")}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const toggleFavorite=id=>{const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem("nanomed_favorite_materials",JSON.stringify(next))};
 const filtered=useMemo(()=>materials.filter(m=>`${m.name} ${m.formula} ${m.crystal_structure||""}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(favorites.includes(b.id)-favorites.includes(a.id))),[materials,search,favorites]);
 const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{await api.post("/materials",{...form,density:parseFloat(form.density),atomic_number:parseFloat(form.atomic_number),atomic_mass:parseFloat(form.atomic_mass),particle_size_nm:form.particle_size_nm?parseFloat(form.particle_size_nm):null});setForm(EMPTY_FORM);setShowForm(false);load()}catch(e){setError(e.response?.data?.detail||"Could not save material")}finally{setSaving(false)}};
 const remove=async id=>{if(id.startsWith("seed-"))return;try{await api.delete(`/materials/${id}`);load()}catch(e){setError("Could not delete material")}};
 const presets=[{name:"ZnO",formula:"ZnO",density:"5.61"},{name:"BaSO₄",formula:"BaSO4",density:"4.50"},{name:"Fe₃O₄",formula:"Fe3O4",density:"5.15"},{name:"Fe₂O₃",formula:"Fe2O3",density:"5.24"},{name:"CaCO₃",formula:"CaCO3",density:"2.71"}];
 const usePreset=p=>{setForm({...EMPTY_FORM,name:p.name,formula:p.formula,density:p.density});setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="space-y-6"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><p className="label-eyebrow">Material intelligence</p><h1 className="font-display text-2xl font-semibold text-ink flex items-center gap-2 mt-1"><Beaker className="text-beam" size={24}/> Materials</h1><p className="text-ink/50 text-sm mt-1">Your private material library, ready to flow into every calculator and simulation.</p></div><div className="flex gap-2"><button onClick={()=>navigate("/dashboard/calculators")} className="px-4 py-2.5 rounded-xl border border-ink/10 bg-white text-sm font-semibold flex items-center gap-2"><Calculator size={16}/> Calculator</button><button onClick={()=>setShowForm(v=>!v)} className="btn-primary">{showForm?<X size={18}/>:<Plus size={18}/>} {showForm?"Cancel":"Add Material"}</button></div></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Mini label="Total materials" value={materials.length}/><Mini label="Favorites" value={favorites.length}/><Mini label="User-created" value={materials.filter(m=>!m.id.startsWith("seed-")).length}/><Mini label="Reference" value={materials.filter(m=>m.id.startsWith("seed-")).length}/></div>
 {showForm&&<motion.form initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} onSubmit={submit} className="glass-panel-light p-6 rounded-2xl grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})} required/><Field label="Formula" value={form.formula} onChange={v=>setForm({...form,formula:v})} required/><Field label="Density (g/cm³)" type="number" step="any" value={form.density} onChange={v=>setForm({...form,density:v})} required/><Field label="Atomic Number (Z)" type="number" step="any" value={form.atomic_number} onChange={v=>setForm({...form,atomic_number:v})} required/><Field label="Atomic Mass (g/mol)" type="number" step="any" value={form.atomic_mass} onChange={v=>setForm({...form,atomic_mass:v})} required/><Field label="Particle Size (nm)" type="number" step="any" value={form.particle_size_nm} onChange={v=>setForm({...form,particle_size_nm:v})}/><Field label="Crystal Structure" value={form.crystal_structure} onChange={v=>setForm({...form,crystal_structure:v})}/><Field label="Manufacturer" value={form.manufacturer} onChange={v=>setForm({...form,manufacturer:v})}/><div className="md:col-span-3"><Field label="Research Notes" value={form.research_notes} onChange={v=>setForm({...form,research_notes:v})} textarea/></div>{error&&<p className="md:col-span-3 text-sm text-red-500">{error}</p>}<div className="md:col-span-3"><button type="submit" disabled={saving} className="btn-primary">{saving?"Saving…":"Save Material"}</button></div></motion.form>}
 <div className="glass-panel-light rounded-2xl p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3.5 text-ink/35"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by material, formula or crystal structure…" className="w-full bg-white border border-ink/10 rounded-xl pl-10 pr-4 py-3 text-sm outline-none focus:border-beam"/></div></div>
 <div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-mono uppercase tracking-widest text-ink/40 mr-1">Quick presets</span>{presets.map(p=><button key={p.formula} onClick={()=>usePreset(p)} className="px-3 py-2 rounded-xl bg-white border border-ink/10 text-xs font-semibold hover:border-beam/30 transition">{p.name}<span className="font-mono text-beam ml-1">{p.formula}</span></button>)}</div>
 {loading?<p className="text-ink/40 text-sm">Loading materials…</p>:<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(m=><motion.div key={m.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="glass-panel-light p-5 rounded-2xl relative group"><div className="flex justify-between gap-3"><div><p className="font-display font-semibold text-ink">{m.name}</p><p className="text-xs font-mono text-beam mt-0.5">{m.formula}</p></div><button onClick={()=>toggleFavorite(m.id)} className={`w-8 h-8 rounded-lg flex items-center justify-center ${favorites.includes(m.id)?"bg-amber-400/15 text-amber-500":"bg-black/5 text-ink/25"}`}><Star size={15} fill={favorites.includes(m.id)?"currentColor":"none"}/></button></div><div className="grid grid-cols-2 gap-2 mt-4 text-xs"><Info label="Density" value={`${m.density} g/cm³`}/><Info label="Z" value={m.atomic_number}/><Info label="Atomic Mass" value={`${m.atomic_mass} g/mol`}/><Info label="Size" value={m.particle_size_nm?`${m.particle_size_nm} nm`:"—"}/></div>{m.research_notes&&<p className="text-xs text-ink/50 mt-3 leading-relaxed line-clamp-3">{m.research_notes}</p>}<div className="flex gap-2 mt-4"><button onClick={()=>navigate(`/dashboard/calculators?material=${encodeURIComponent(m.id)}`)} className="flex-1 rounded-xl bg-beam/10 text-beam py-2 text-xs font-semibold flex items-center justify-center gap-1.5"><Calculator size={14}/> Use in calculator</button>{!m.id.startsWith("seed-")&&<button onClick={()=>remove(m.id)} className="w-10 rounded-xl border border-ink/10 text-ink/30 hover:text-red-500 flex items-center justify-center"><Trash2 size={15}/></button>}</div></motion.div>)}{!filtered.length&&<div className="col-span-full py-14 text-center text-ink/40"><FlaskConical size={30} className="mx-auto mb-2"/>No materials match your search.</div>}</div>}</div>
}
function Field({label,value,onChange,type="text",textarea,...rest}){const Comp=textarea?"textarea":"input";return <div className="space-y-1.5"><label className="text-xs font-mono uppercase tracking-wide text-ink/50">{label}</label><Comp type={type} value={value} onChange={e=>onChange(e.target.value)} rows={textarea?3:undefined} className="w-full bg-white border border-ink/15 rounded-xl px-3 py-2.5 text-sm text-ink focus:border-beam outline-none" {...rest}/></div>}
function Info({label,value}){return <div><p className="text-ink/40">{label}</p><p className="font-mono text-ink">{value}</p></div>}; function Mini({label,value}){return <div className="glass-panel-light rounded-2xl p-4"><p className="text-xs text-ink/45">{label}</p><p className="text-2xl font-display font-semibold mt-1">{value}</p></div>}
