import { useEffect, useState } from 'react';
import { Beaker, CheckCircle2, ClipboardList, FlaskConical, Plus, Trash2, WandSparkles } from 'lucide-react';
import api from '../lib/api';

const blank={title:'',objective:'',material:'',energy_kev:'',thickness_cm:'',detector:'Geiger-Muller counter',notes:'',status:'Planned'};
export default function ResearchStudio(){
 const [templates,setTemplates]=useState([]),[experiments,setExperiments]=useState([]),[form,setForm]=useState(blank),[selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const [t,e]=await Promise.all([api.get('/research-studio/templates'),api.get('/research-studio/experiments')]);setTemplates(t.data);setExperiments(e.data)};
 useEffect(()=>{load().catch(()=>setMessage('Unable to load Research Studio.'))},[]);
 const update=(k,v)=>setForm(x=>({...x,[k]:v}));
 const useTemplate=(t)=>setForm({...blank,title:t.name,objective:t.objective,detector:t.detector});
 const save=async(e)=>{e.preventDefault(); if(!form.title.trim())return; setSaving(true); try{const r=await api.post('/research-studio/experiments',{...form,energy_kev:form.energy_kev?Number(form.energy_kev):null,thickness_cm:form.thickness_cm?Number(form.thickness_cm):null});setExperiments(x=>[r.data,...x]);setForm(blank);setMessage('Experiment saved to your workspace.')}catch{setMessage('Could not save experiment.')}finally{setSaving(false)}};
 const remove=async(id)=>{if(!confirm('Delete this experiment?'))return; await api.delete(`/research-studio/experiments/${id}`);setExperiments(x=>x.filter(e=>e.id!==id)); if(selected?.id===id)setSelected(null)};
 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-br from-[#082f3a] via-[#0b5b62] to-[#087f78] p-7 text-white shadow-xl"><p className="text-[10px] uppercase tracking-[.25em] text-sage-200/80">Research Studio</p><h1 className="font-display text-3xl font-semibold mt-2">Build, organize and validate experiments.</h1><p className="text-sm text-white/65 max-w-2xl mt-3">Create structured experiment plans and keep radiation, material and detector metadata attached to each research run.</p></section>
  {message&&<div className="rounded-xl bg-sage-50 border border-sage-200 px-4 py-3 text-sm text-sage-800">{message}</div>}
  <div className="grid xl:grid-cols-[.8fr_1.2fr] gap-6">
   <div className="glass-panel-light rounded-2xl p-5"><div className="flex items-center gap-2"><WandSparkles size={18} className="text-sage-600"/><div><p className="label-eyebrow">Templates</p><h2 className="font-display text-xl font-semibold">Start from a protocol</h2></div></div><div className="mt-4 space-y-3">{templates.map(t=><button key={t.id} onClick={()=>useTemplate(t)} className="w-full text-left rounded-xl border border-slate-200 bg-white p-4 hover:border-sage-400 hover:bg-sage-50/40 transition"><div className="flex items-center justify-between"><span className="font-semibold text-sm">{t.name}</span><ClipboardList size={15} className="text-sage-600"/></div><p className="text-xs text-ink/50 mt-2">{t.objective}</p><p className="text-[10px] text-ink/35 mt-2">Detector: {t.detector}</p></button>)}</div></div>
   <form onSubmit={save} className="glass-panel-light rounded-2xl p-5"><div className="flex items-center gap-2"><FlaskConical size={18} className="text-sage-600"/><div><p className="label-eyebrow">Experiment builder</p><h2 className="font-display text-xl font-semibold">New experiment</h2></div></div><div className="grid sm:grid-cols-2 gap-3 mt-5">
    {[["title","Experiment title"],["material","Material"],["energy_kev","Energy (keV)"],["thickness_cm","Thickness (cm)"],["detector","Detector"]].map(([k,l])=><label key={k} className="text-xs font-medium text-ink/60">{l}<input value={form[k]} onChange={e=>update(k,e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-sage-400" /></label>)}
    <label className="text-xs font-medium text-ink/60">Status<select value={form.status} onChange={e=>update('status',e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option>Planned</option><option>In Progress</option><option>Completed</option></select></label>
   </div><label className="block text-xs font-medium text-ink/60 mt-3">Research objective<textarea value={form.objective} onChange={e=>update('objective',e.target.value)} rows="3" className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-sage-400"/></label><label className="block text-xs font-medium text-ink/60 mt-3">Notes<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} rows="2" className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-sage-400"/></label><button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-sage-700 text-white px-4 py-3 text-sm font-semibold hover:bg-sage-800 disabled:opacity-50"><Plus size={16}/>{saving?'Saving…':'Save experiment'}</button></form>
  </div>
  <section className="glass-panel-light rounded-2xl p-5"><div className="flex items-center gap-2"><Beaker size={18} className="text-sage-600"/><div><p className="label-eyebrow">Experiment registry</p><h2 className="font-display text-xl font-semibold">Saved protocols</h2></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-4">{experiments.map(e=><div key={e.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-2"><div><h3 className="font-semibold text-sm">{e.title}</h3><p className="text-[11px] text-ink/45 mt-1">{e.material||'Material not set'} · {e.energy_kev?`${e.energy_kev} keV`:'Energy not set'}</p></div><span className="text-[10px] rounded-full bg-sage-50 text-sage-700 px-2 py-1 h-fit">{e.status}</span></div><p className="text-xs text-ink/55 mt-3 line-clamp-2">{e.objective||'No objective added.'}</p><div className="flex justify-end mt-4"><button onClick={()=>remove(e.id)} className="p-2 rounded-lg hover:bg-red-50 text-red-500"><Trash2 size={14}/></button></div></div>)}{!experiments.length&&<div className="col-span-full py-8 text-center text-xs text-ink/40">No experiments yet. Choose a template to get started.</div>}</div></section>
 </div>
}
